spring.application.name=notification-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/orderhandler_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.show-sql=true