spring.application.name=order-service
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# GRPC client settings
grpc.client.InventoryServiceGRPCClient.address=localhost:9090
grpc.client.InventoryServiceGRPCClient.negotiation-type=plaintext

spring.datasource.url=jdbc:postgresql://localhost:5432/orderhandler_db
spring.datasource.password=12345678
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver