#docker launch
spring.kafka.bootstrap-servers=kafka:9092

grpc.client.inventorygrpcclient.address=inventory-service:9090

spring.datasource.url=jdbc:postgresql://order-handler-postgresDB:5432/order_handler_postgresDB