syntax = "proto3";
package com.coolcupp.inventoryService.grpc;

option java_multiple_files = true;

message ProductResponseItem {
  int64 id = 1;
  string name = 2;
  int32 requestedQuantity = 3;
  string price = 4;
  string discountPercent = 5;
  int32 quantityInStorage = 6;
  bool isAvailability = 7;
}

message ProductRequestItem {
  int64 id = 1;
  int32 requestedQuantity = 2;
}

// list of product item - request
message ProductTotalRequest {
  repeated ProductRequestItem items = 1;
}

// lists of availability, unavailability  - response
message ProductTotalResponse {
  repeated ProductResponseItem availabilityItems = 1;
  repeated ProductResponseItem unavailabilityItems = 2;
}

service InventoryService {
  rpc CheckAvailability(ProductTotalRequest) returns (ProductTotalResponse);
}